routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PostsController@index');
Auth::routes();

Route::group(['middleWare' => 'auth'], function () {
    Route::get('/home', 'PostsController@index')->name('home');
    Route::resource('posts', 'PostsController');
    Route::resource('comments', 'CommentsController');
    Route::get('userPosts', 'PostsController@userPosts');
});

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    protected $fillable = [
        'body',
        'user_id',
        'post_id'
    ];

    public function post()
    {
        return $this->belongsTo(Post::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = [
        'title',
        'body',
        'user_id'
    ];

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function users()
    {
        return $this->belongsTo(User::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}

app/Http/Controllers/CommentsController.php
<?php

namespace App\Http\Controllers;

use App\Comment;
use App\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class CommentsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = Auth::user();
        $comments = Comment::where('user_id', '=', $user->id)->orderby('id', 'desc')->paginate(20);
        return view('user.comments.index', compact('comments'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'body' => 'required',
            'post_id' => 'required|integer'
        ]);

        $input = $request->all();
        $input['user_id'] = Auth::id();

        Comment::create($input);

        return redirect()->route('posts.show', $input['post_id']);

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function show(Comment $comment)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function edit(Comment $comment)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Comment $comment)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function destroy(Comment $comment)
    {
        $comment->delete();

        return redirect()->route('comments.index');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/PagesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class PagesController extends Controller
{
    public function index()
    {
        return view('welcome', ['list' => 5]);
    }
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use App\Comment;
use App\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class PostsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::orderby('id', 'desc')->paginate(10);
        return view('user.posts.all', compact('posts'));
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function userPosts()
    {
        $user = Auth::user();
        $posts = Post::where('user_id', '=', $user->id)->orderby('id', 'desc')->paginate(10);

        return view('user.posts.userPosts', compact('posts'));
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.posts.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
            'body' => 'required',
        ]);

        $input = $request->all();
        $input['user_id'] = Auth::id();

        Post::create($input);

        return redirect('/userPosts');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Post $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        $post = Post::where('id', '=', $post->id)->first();
        $comments = Comment::where('post_id', '=', $post->id)->orderby('id', 'desc')->paginate(10);

        return view('user.posts.single', ['post' => $post, 'comments' => $comments]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Post $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        $post->delete();

        return redirect('/userPosts');
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Simple Blog</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
<div id="app">
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#app-navbar-collapse" aria-expanded="false">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ url('/') }}">
                    Simple Blog
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                @guest
                @else
                    <ul class="nav navbar-nav">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true"
                               aria-expanded="false">Posts <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="{{route('posts.create')}}">Create post</a></li>
                                <li><a href="{{route('posts.index')}}">All posts</a></li>
                                <li><a href="{{url('/userPosts')}}">My posts</a></li>
                            </ul>
                        </li>
                        <li><a href="{{route('comments.index')}}">Comments</a></li>
                    </ul>
                @endguest
                <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @guest
                        <li><a href="{{ route('login') }}">Login</a></li>
                        <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                                   aria-expanded="false" aria-haspopup="true">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                           onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                              style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                            @endguest
                    </ul>
            </div>
        </div>
    </nav>

    @yield('content')
</div>

<!-- Scripts -->
<script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/user/comments/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Comments</div>
                    <div class="panel-body">
                        @if($comments->count() > 0)
                            <table class="table">
                                <tr>
                                    <th>Comment ID</th>
                                    <th>Post ID</th>
                                    <th>Text</th>
                                    <th>Actions</th>
                                </tr>
                                @foreach($comments as $comment)
                                    <tr>
                                        <td>{{$comment->id}}</td>
                                        <td>{{$comment->post_id}}</td>
                                        <td>{{$comment->body}}</td>
                                        <td>
                                            <form method="post" action="{{route('comments.destroy', $post->id)}}">
                                                {{ method_field('DELETE') }}
                                                {{ csrf_field() }}
                                                <div class="form-group">
                                                    <button type="submit" class="btn btn-danger">Delete</button>
                                                </div>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                            </table>
                            <div class="text-center">
                                {{$comments->links()}}
                            </div>
                        @else
                            You have no comments yet.
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user/posts/all.blade.php
@extends('welcome')

@section('posts')
    <div class="panel panel-body">
        <div class="blog-main">
            @if($posts->total() > 0)
                @foreach($posts as $post)
                    <div class="blog-post">
                        <a href="{{route('posts.show', $post->id)}}">
                            <h2 class="blog-post-title">{{$post->title}}</h2>
                        </a>
                        <p class="blog-post-meta">
                            Author: {{\App\User::find($post->user_id)->name}}
                        </p>
                        <p>{{$post->body}}</p>
                    </div>
                    <hr>
                @endforeach
                <div class="text-center">
                    {{$posts->links()}}
                </div>
            @else
                <p>No posts found. Please log in and create some.</p>
            @endif
        </div>
    </div>
@endsection

resources/views/user/posts/form.blade.php
@extends('welcome')


@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Create post</div>
                    <div class="panel-body">
                        <ul>
                            @foreach($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>

                        {!! Form::open(array('route' => 'posts.store', 'class' => 'form')) !!}

                        <div class="form-group">
                            {!! Form::label('Title') !!}
                            {!! Form::text('title', null,
                                array('required',
                                      'class'=>'form-control',
                                      'placeholder'=>'Post title')) !!}
                        </div>

                        <div class="form-group">
                            {!! Form::label('Body') !!}
                            {!! Form::textarea('body', null,
                                array('required',
                                      'class'=>'form-control',
                                      'placeholder' => 'Post text')) !!}
                        </div>

                        <div class="form-group">
                            {!! Form::submit('Add post',
                              array('class'=>'btn btn-primary')) !!}
                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user/posts/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">My posts</div>
                    <div class="panel-body">
                        @if($posts->count() > 0)
                            <table class="table">
                                <tr>
                                    <th>Post ID</th>
                                    <th>Title</th>
                                    <th>Text</th>
                                    <th>Actions</th>
                                </tr>
                                @foreach($posts as $post)
                                    <tr>
                                        <td>{{$post->id}}</td>
                                        <td>{{$post->title}}</td>
                                        <td>{{$post->body}}</td>
                                        <td>
                                            <a class="btn btn-danger" type="button"
                                               href="{{route('comments.destroy', $post->id)}}">
                                                Delete
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                            </table>
                            <div class="text-center">
                                {{$posts->links()}}
                            </div>
                        @else
                            You have no comments yet.
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user/posts/single.blade.php
@extends('welcome')

@section('posts')
    <div class="panel panel-body">
        <div class="blog-main">
            @if($post->count() > 0)
                <div class="blog-post">
                    <h2 class="blog-post-title">{{$post->title}}</h2>
                    <p class="blog-post-meta">
                        Author: {{\App\User::find($post->user_id)->name}}
                    </p>
                    <p>{{$post->body}}</p>
                </div>
            @else
                <p>No posts found. Please log in and create some.</p>
            @endif
        </div>
    </div>
    <div class="panel panel-body">
        <div class="comments-list">
            <h3 class="panel-heading text-center">Comments</h3>
            @if($comments->count() > 0)
                @foreach($comments as $comment)
                    <h4 class="media-heading user_name">{{\App\User::find($comment->user_id)->name}}</h4>
                    <p>{{$comment->body}}</p>
                    <hr>
                @endforeach
                <div class="text-center">
                    {{$comments->links()}}
                </div>
            @else
                <p>Post has no comments.</p>
            @endif
        </div>
        @guest
        <p>Please sign up or log in to be able write comments.</p>
        @else
            {!! Form::open(['route' => 'comments.store', 'class' => 'form']) !!}

            {!! Form::hidden('post_id', $post->id ) !!}

            <div class="form-group">
                {!! Form::label('Comment') !!}
                {!! Form::textarea('body', null,
                    array('required',
                          'class'=>'form-control')) !!}
            </div>

            <div class="form-group">
                {!! Form::submit('Add comment',
                  array('class'=>'btn btn-primary')) !!}
            </div>
            {!! Form::close() !!}
            @endguest
    </div>
@endsection

resources/views/user/posts/userPosts.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">My posts</div>
                    <div class="panel-body">
                        @if($posts->count() > 0)
                            <table class="table">
                                <tr>
                                    <th>Post ID</th>
                                    <th>Title</th>
                                    <th>Text</th>
                                    <th>Actions</th>
                                </tr>
                                @foreach($posts as $post)
                                    <tr>
                                        <td>{{$post->id}}</td>
                                        <td>{{$post->title}}</td>
                                        <td>{{$post->body}}</td>
                                        <td>
                                            <form method="post" action="{{route('posts.destroy', $post->id)}}">
                                                {{ method_field('DELETE') }}
                                                {{ csrf_field() }}
                                                <div class="form-group">
                                                    <button type="submit" class="btn btn-danger">Delete</button>
                                                </div>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                            </table>
                            <div class="text-center">
                                {{$posts->links()}}
                            </div>
                        @else
                            You have no comments yet.
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection